name: "Generate Base64 Keystore (Run Once)"
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore android-debug.jks -alias trackail -keyalg RSA -keysize 2048 -validity 36500 -storepass android -keypass android -dname "CN=Trackail, O=Simon, C=CN"
      
      - name: Convert to Base64
        run: |
          echo "==== 请完整复制以下全部内容（不含横线）： ===="
          echo "--------------------------------------------------------"
          base64 android-debug.jks | tr -d '\n\r'
          echo ""
          echo "--------------------------------------------------------"
          echo "==== 复制结束 ===="
